# Generated by Django 3.2.7 on 2021-11-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_delete_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='Address', max_length=200, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='LastName', max_length=30, verbose_name='LastName'),
        ),
    ]
